#!/bin/sh

sudo pacman -Sy \
     acpi \
     adobe-source-code-pro-fonts \
     adobe-source-han-sans-cn-fonts \
     adobe-source-han-serif-cn-fonts \
     alacritty \
     alsa-utils \
     android-file-transfer \
     ansible \
     ansible-lint \
     arc-gtk-theme \
     arc-icon-theme \
     arch-wiki-docs \
     aria2 \
     base-devel \
     bind-tools \
     blender \
     bucklespring \
     buildah \
     cdrkit \
     chromium \
     clang \
     deepin-screenshot \
     dmenu \
     dunst \
     efibootmgr \
     fcitx \
     fcitx-configtool \
     fcitx-gtk2 \
     fcitx-gtk3 \
     fcitx-qt5 \
     feh \
     ffmpeg \
     gimp \
     git \
     goldendict \
     google-chrome \
     grub \
     gvfs \
     gvfs-mtp \
     htop \
     httpie \
     i3-wm \
     i3status-rust \
     imwheel \
     inkscape \
     iwd \
     kchmviewer \
     lftp \
     libnotify \
     llvm \
     llvm-libs \
     man-db \
     mesa \
     mitmproxy \
     mpv \
     mupdf-tools \
     net-tools \
     network-manager-applet \
     networkmanager \
     nmap \
     nodejs \
     npm \
     nvidia \
     nvidia-settings \
     nvidia-utils \
     openbsd-netcat \
     openssh \
     playerctl \
     pngquant \
     podman \
     poppler-data \
     postgresql-docs \
     privoxy \
     python-docs \
     python-gobject \
     python-pysocks \
     python-pytest \
     python-requests \
     ripgrep \
     rsync \
     sakura \
     screenkey \
     shadowsocks \
     simplescreenrecorder \
     syslinux \
     tk \
     tmux \
     tmuxp \
     tokei \
     trash-cli \
     tree \
     ttf-dejavu \
     unrar \
     unzip \
     usbutils \
     vagrant \
     valgrind \
     vim \
     virtualbox \
     virtualbox-guest-iso \
     virtualbox-host-modules-arch \
     visual-studio-code-bin \
     vulkan-headers \
     vulkan-icd-loader \
     vulkan-intel \
     vulkan-tools \
     vulkan-validation-layers \
     wget \
     wps-office \
     xclip \
     xf86-video-intel \
     xorg-apps  \
     xorg-server \
     xorg-xinit \
     yay \
     zathura \
     zathura-djvu \
     zathura-pdf-mupdf \
     zathura-ps \
     zsh \
     zsh-completions \


# yay -S spacefm
#    - pacman -S powerline-fonts
#    - pacman -S ttf-font-awesome
# yay -S mpv-mpris
# yay -S devdocs-desktop-bin
# yay -S woeusb-ng
