fpath+=~/.zsh/completion

HISTFILE=~/.zsh_histfile
HISTSIZE=10000
SAVEHIST=10000
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history
setopt hist_find_no_dups
setopt hist_reduce_blanks
setopt hist_save_no_dups
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

bindkey -e
bindkey '^r'        history-incremental-search-backward
bindkey ' '         magic-space    # Space -> history expansion
bindkey '^[[1;5C'   forward-word   # Ctrl-Right
bindkey '^[[1;5D'   backward-word  # Ctrl-Left
bindkey "^[[A"      up-line-or-beginning-search   # Up
bindkey "^[[B"      down-line-or-beginning-search # Down
bindkey "^p"        up-line-or-beginning-search   # C-p
bindkey "^n"        down-line-or-beginning-search # C-n
bindkey "^[[3~"     delete-char                   # DEL

DIRSTACKSIZE=10
setopt autocd
setopt autopushd
setopt pushdminus
setopt pushdsilent
setopt pushdtohome
setopt pushd_ignore_dups
alias -g ...='../..'
alias -g ....='../../..'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
alias d='dirs -v'

setopt multios
setopt extended_glob
setopt interactivecomments

autoload -U compinit && compinit
zstyle ':completion:*' menu select
# source ~/.zsh/skim/completion.zsh
# source ~/.zsh/skim/key-bindings.zsh

alias ls='ls --color=tty'
alias ll='ls -lh'
alias la='ls -a'
alias https='http --default-scheme=https'

export LANG=en_US.UTF-8
export LC_COLLATE=zh_CN.UTF-8
export SYSTEMD_LESS=FRXMK
export VISUAL=vim
export EDITOR=vim

typeset -U path
path=(~/.pyenv/bin
      ~/.rbenv/bin
      ~/.cargo/bin
      ~/.golang/bin
      ~/.local/bin
      ~/.node_modules/bin
      /opt/flutter/bin
      /opt/android-sdk/tools/bin
      /opt/android-sdk/platform-tools
      $path)

# libvirt
export LIBVIRT_DEFAULT_URI="qemu:///system"

# starship
eval "$(starship init zsh)"

# git
# source ~/.zsh/git.zsh
# autoload -U colors && colors
# PROMPT='%{$fg[yellow]%}%~%{$reset_color%}$(git_super_status)$ '

# tab multiplexer
# source ~/.local/share/tab/completion/zsh-history.zsh

# nodejs
export npm_config_prefix=~/.node_modules

# python
# eval "$(pyenv init - --no-rehash)"
# source ~/.local/bin/virtualenv-autodetect.sh

# ruby
eval "$(rbenv init -)"

# rust
export RUSTUP_DIST_SERVER=https://mirrors.sjtug.sjtu.edu.cn/rust-static
export RUSTUP_UPDATE_ROOT=https://mirrors.sjtug.sjtu.edu.cn/rust-static/rustup
export RUST_SRC_PATH=~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu

# go
export GOPROXY=https://goproxy.io,direct
export GOPATH=~/.golang
export GO111MODULE=on
export GOROOT=/usr/lib/go

# ocaml
# test -r ~/.opam/opam-init/init.zsh && . ~/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
# eval $(opam env)

# swift
# export SWIFTENV_ROOT="$HOME/.swiftenv"
# export PATH="$SWIFTENV_ROOT/bin:$PATH"
# eval "$(swiftenv init -)"

# java
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'

# android sdk
export ANDROID_HOME=/opt/android-sdk
# android tools
export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'

# flutter
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

function http_proxy_on() {
    export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"

    if (( $# > 0 )); then
        valid=$(echo $@ | sed -n 's/\([0-9]\{1,3\}.\)\{4\}:\([0-9]\+\)/&/p')
        if [[ $valid != $@ ]]; then
            >&2 echo "Invalid address"
            return 1
        fi
        export http_proxy="http://$1/"
    else
        export http_proxy="127.0.0.1:10080"
    fi

    export https_proxy=$http_proxy
    export ftp_proxy=$http_proxy
    export rsync_proxy=$http_proxy
    export HTTP_PROXY=$http_proxy
    export HTTPS_PROXY=$http_proxy
    export FTP_PROXY=$http_proxy
    export RSYNC_PROXY=$http_proxy
    echo "Proxy environment variable set: $http_proxy"
    return 0
}

function http_proxy_off(){
    unset http_proxy
    unset https_proxy
    unset ftp_proxy
    unset rsync_proxy
    unset HTTP_PROXY
    unset HTTPS_PROXY
    unset FTP_PROXY
    unset RSYNC_PROXY
    echo "Proxy environment variable removed."
}

function proxy_on() {
    if (( $# > 0 )); then
        valid=$(echo $@ | sed -n 's/\([0-9]\{1,3\}.\)\{4\}:\([0-9]\+\)/&/p')
        if [[ $valid != $@ ]]; then
            >&2 echo "Invalid address"
            return 1
        fi
        export all_proxy="socks5://$1"
    else
        export all_proxy="socks5://127.0.0.1:1080"
    fi
    echo "Proxy environment variable set: $all_proxy"
    return 0
}

function proxy_off(){
    unset all_proxy
    echo "Proxy environment variable removed."
}
