code --install-extension abhi18av-vscode.chez-scheme-vscode
code --install-extension basdp.language-gas-x86
code --install-extension bungcip.better-toml
code --install-extension ChandZhang.wechat-snippet
code --install-extension christian-kohler.path-intellisense
code --install-extension cnyballk.wxml-vscode
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension daohong-emilio.yash
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension golang.go
code --install-extension humao.rest-client
code --install-extension matklad.rust-analyzer
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension octref.vetur
code --install-extension qiu8310.minapp-vscode
code --install-extension samuelcolvin.jinjahtml
code --install-extension serayuzgur.crates
code --install-extension vscodevim.vim
