theme = "plain"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "{percentage}({available})"
interval = 20

[[block]]
block = "net"
device = "wlp5s0"
format = "{ssid} {signal_strength} {ip}"
interval = 5

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength} {ip}"
interval = 5

[[block]]
block = "sound"
step_width = 10

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 10
format = "%Y-%m-%d(%u)%H:%M"
